import Head from "next/head";
import Link from "next/link";
import { SignIn, SignUp, useUser, UserButton } from "@clerk/nextjs";

import { api } from "~/utils/api";

export default function Home() {
  const user = useUser();
  console.log(user)
  
  const { data } = api.events.getAll.useQuery();

  //If a user is logged in, check DB to see if they exist in the DB, if not prompt with component
  function doesUserExist() {
    // Check Db if user exists via email, if so do nothing, if not send to finish registration page
    const userEmail = user?.user?.primaryEmailAddress?.emailAddress;
    if (userEmail) {
      const { data } = api.users.getUserByEmail.useQuery(userEmail);
      console.log(data);
      if (!data) {
        return false
      }
    }
    return true
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <SignIn />
        <UserButton />
        {!!user && !doesUserExist() ? <div>Please complete your registration</div> : ""} 
        <div>
          <h1>Upcoming Events:</h1>
          {data?.map((event) => (
            <div key={event.id}>
              <span>{event.name} </span>
              <span>{event.location} </span>
              <span>{new Date(event.start).toString()} </span>
            </div>
          ))}
        </div>
      </main>
    </>
  );
}
