import Head from "next/head";
import Link from "next/link";
import { SignIn, SignUp, useUser, UserButton } from "@clerk/nextjs";

import { api } from "~/utils/api";

export default function Home() {
  const user = useUser();
  console.log(user)
  
  const { data } = api.events.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <SignIn />
        <UserButton />
        <div>
          <h1>Upcoming Events:</h1>
          {data?.map((event) => (
            <div key={event.id}>
              <span>{event.name} </span>
              <span>{event.location} </span>
              <span>{new Date(event.start).toString()} </span>
            </div>
          ))}
        </div>
      </main>
    </>
  );
}
