import Head from "next/head";
import Register from "../components/register";
import { SignIn, SignUp, useUser, UserButton } from "@clerk/nextjs";

import { api } from "~/utils/api";

export default function Home() {
  const user = useUser();
  console.log(user)
  
  const { data: eventData } = api.events.getAll.useQuery();
  //TODO remove need for empty string
  const userEmail = user?.user?.primaryEmailAddress?.emailAddress || "";
  const { data: userData} = api.users.getUserByEmail.useQuery(userEmail);

  const isUserRegistered = doesUserExist();

  //If a user is logged in, check DB to see if they exist in the DB, if not prompt with component
  function doesUserExist() {
    return !!userData;
  }

  return (
    <>
      <Head>
        <title>Schedule.me</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <SignIn />
        <UserButton />
        {!!user && !isUserRegistered ? <Register /> : ""} 
        <div>
          <h1>Upcoming Events:</h1>
          {eventData?.map((event) => (
            <div key={event.id}>
              <span>{event.name} </span>
              <span>{event.location} </span>
              <span>{new Date(event.start).toString()} </span>
            </div>
          ))}
        </div>
      </main>
    </>
  );
}
